#pragma config(Motor,  port1,           puncher1,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           craneAdjust,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           craneL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           intakeStuff,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           driveL,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           driveR1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           driveR2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           craneR,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           craneRotate,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          puncher2,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	//basic autonomous


				//far side
				//move forward
/*
				motor[driveL] = -127;
				motor[driveR1] = 127;
				motor[driveR2] = 127;
				delay(900);
				motor[driveL] = 0;
				motor[driveR1] = 0;
				motor[driveR2] = 0;
				motor[craneAdjust] = 60;
				delay(500);
				motor[craneAdjust] = 0;
				//shoot
				motor[puncher1] = 127;
				motor[puncher2] = -127;
				delay(1000);
				//back up
				motor[driveL] = 127;
				motor[driveR1] = -127;
				motor[driveR2] = -127;
				delay(900);
				//shut off
				motor[driveL] = 0;
				motor[driveR1] = 0;
				motor[driveR2] = 0;
				motor[puncher1] = 0;
				motor[puncher2] = 0;
				*/

		//near side

				//move forward
				motor[driveL] = -127;
				motor[driveR1] = 127;
				motor[driveR2] = 127;
				delay(600);
				motor[driveL] = 0;
				motor[driveR1] = 0;
				motor[driveR2] = 0;
				motor[craneAdjust] = 60;
				delay(500);
				motor[craneAdjust] = 0;
				//shoot
				motor[puncher1] = 127;
				motor[puncher2] = -127;
				delay(1200);
				motor[puncher1] = 0;
				motor[puncher2] = 0;
				//turn a bit all negs if red, otherwise pos if blue
				motor[driveL] = 127;
				motor[driveR1] = 127;
				motor[driveR2] = 127;
				delay(75);
				//ramming speed
				motor[driveL] = -127;
				motor[driveR1] = 127;
				motor[driveR2] = 127;
				delay(1800);
				//shut off
				motor[driveL] = 0;
				motor[driveR1] = 0;
				motor[driveR2] = 0;
				motor[puncher1] = 0;
				motor[puncher2] = 0;

	//*****************************************************************************************************************//
	//experimental auton
			//near side

				//go forward, ram into cap
				motor[driveL] = -127;
				motor[driveR1] = 127;
				motor[driveR2] = 127;
				motor[intakeStuff] = -127;
				delay(1500);
				//grab ball underneath
				motor[intakeStuff] = -127;
				delay(1000);
				//go back to start position
				motor[driveL] = 127;
				motor[driveR1] = -127;
				motor[driveR2] = -127;
				delay(1500);
				//turn [left/right] depending on team color

				//shoot high flag

				//move forward a little bit

				//shoot mid flag

				//ram into low flag

				//shut off all motors

			//far side
				//move forward ram into cap

				//grab ball underneath

				//turn [left/right] depending on team color

				//move forward onto the parking platform

				//turn bot to shoot at mid flags

				//shoot at mid flags

				//turn more to shoot at enemy flags

				//shoot at enemy flag (useful if enemy shoots their mid flag)




}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop
	/*int j3;
	int j4;

	int s4;
	int s5;
*/
	int switchControls=0;
	int btn8Rold;

	int intakeVariable = 0;
	while (true)
	{
		/*movement arcade drive
		j3 = vexRT[Ch3];
		j4 = vexRT[Ch4];

		s4 = (j3 + j4);
		s5 = -(j3 - j4);

		if( s4 > 127){
			s4 = 127;
		}
		if (s4 < -127){
			s4 = -127;
		}

		if( s5 > 127){
			s5 = 127;
		}
		if (s5 < -127){
			s5 = -127;
		}

		motor[driveL] = s4;
		motor[driveR1] = s5;
		motor[driveR2] = s5; */

		//tank drive
/*
		motor[driveL] = -vexRT[Ch3];

		motor[driveR1] = vexRT[Ch2];
		motor[driveR2] = vexRT[Ch2];
		*/
		//tank drive with switch command
		if(vexRT[Btn6UXmtr2] == 1 && btn8Rold == 0){

		switchControls += 1;
	}
	btn8Rold = vexRT[Btn6UXmtr2];

		if(switchControls % 2 == 0){//Shooter front, Josaiah's preference
		motor[driveL] = -vexRT[Ch3];

		motor[driveR1] = vexRT[Ch2];
		motor[driveR2] = vexRT[Ch2];
	}
	else if(switchControls % 2 != 0){//Crane front, Zaydan's preference
		motor[driveL] = vexRT[Ch3];

		motor[driveR1] = -vexRT[Ch2];
		motor[driveR2] = -vexRT[Ch2];
	}
	else{
		motor[driveL] = 0;

		motor[driveR1] = 0;
		motor[driveR2] = 0;
	}
		//puncher might have to change direction
		if(vexRT[Btn8D] == 1){
			motor[puncher1] = 127;
			motor[puncher2] = -127;
		}
		else {
			motor[puncher1] = 0;
			motor[puncher2] = 0;
		}
		//zaydan's intake lift
		if(vexRT[Btn5U] == 1){
			intakeVariable = 1;
		}
		else if(vexRT[Btn5D] == 1){
			intakeVariable = 0;
		}
		//Eject ball
		else if(vexRT[Btn7L] == 1){
			motor[intakeStuff] = 127;
		}
		//toggles the intake on and off 1 being on and 0 being off
		if (intakeVariable == 1){
			motor[intakeStuff] = -127;
		}else if (intakeVariable == 0){
			motor[intakeStuff] = 0;
		}
		//standard lift

		/*partner crane
		if(vexRT[Btn8DXmtr2] == 1){
			motor[craneL] = 127;
			motor[craneR] = -127;
		}
		else if(vexRT[Btn8UXmtr2] == 1){
			motor[craneL] = -127;
			motor[craneR] = 127;
		}
		else{
			motor[craneL] = 0;
			motor[craneR] = 0;
		}
		*/
		/*
		//main crane
		if(vexRT[Btn8DXmtr2] == 1){
			motor[craneL] = 127;
			motor[craneR] = -127;
		}
		else if(vexRT[Btn8UXmtr2] == 1){
			motor[craneL] = -127;
			motor[craneR] = 127;
		}
		else{
			motor[craneL] = 0;
			motor[craneR] = 0;
		}
		//partner claw adjust
		if(vexRT[Btn7LXmtr2] == 1){
			motor[craneAdjust] = 60;
		}
		else if(vexRT[Btn7RXmtr2] == 1){
			motor[craneAdjust] = -60;
		}
		else{
			motor[craneAdjust] = 0;
		}
		//partner claw rotation
		if(vexRT[Btn7DXmtr2] == 1){
			motor[craneRotate] = 127;
		}
		else if(vexRT[Btn7UXmtr2] == 1){
			motor[craneRotate] = -127;
		}
		else{
			motor[craneRotate] = 0;
		}
		*/

			//auton tester just paste the auton code being used here
			if(vexRT[Btn6D] == 1){

		}
	}
}
